In [1]:
import pandas as pd
from pathlib import Path
import re

In [2]:
RESOURCES_DIRECTORY = Path("./resources")
OUTPUT_DIRECTORY = Path("./output")
OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)

## Clean use groups exported from Excel

### Sample set (UGX only)

In [3]:
use_groups = pd.read_csv(RESOURCES_DIRECTORY / "use_groups.csv")
use_groups

,Use Group,Uses Header,Uses (NAICS Code),R1,R2,R3,R4,R5,R6,R7,...,C3,C4,C5,C6,C7,C8,M1,M2,M3,PRC
0,X,Food Manufacturing (311),Animal food manufacturing (3111),–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–\n,–\n,–\n,–\n,–\n,–\n,●\nP,●\nP,●\nP,D1
1,X,Food Manufacturing (311),Sugar manufacturing (31131),–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–,–,–,–,–,–,●\nP,●\nP,●\nP,D1
2,X,Food Manufacturing (311),All other sugar and confectionary product manu...,–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–\n,●\nS P,●\nS P,●\nS P,●\nS P,●\nP,●\nP,●\nP,●\nP,D1
3,X,Food Manufacturing (311),Animal slaughtering and processing (3116),–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–,–,–,–,–,–,●\nP,●\nP,●\nP,D1
4,X,Food Manufacturing (311),Seafood product preparation and packaging (3117),–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–,–,–,–,–,–,●\nP,●\nP,●\nP,D1
5,X,Food Manufacturing (311),All other food manufacturing (in 311)\n,–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–\n,●\nS P,●\nS P,●\nS P,●\nS P,●\nP,●\nP,●\nP,●\nP,D1
6,X,Beverage and Tobacco Product Manufacturing (312),Distilleries (31214),–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–\n,–\n,–\n,–\n,–\n,–\n,●\nP,●\nP,●\nP,D1
7,X,Beverage and Tobacco Product Manufacturing (312),All other beverage manufacturing \n( in 3121 ),–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–\n,●\nS P,●\nS P,●\nS P,●\nS P,●\nP,●\nP,●\nP,●\nP,D1
8,X,Beverage and Tobacco Product Manufacturing (312),Tobacco manufacturing (3122),–\n,–\n,–\n,–\n,–\n,–\n,–\n,...,–\n,●\nS P,●\nS P,●\nS P,●\nS P,●\nP,●\nP,●\nP,●\nP,D1
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
use_groups_cleaned = (
    use_groups.replace({r"\s+$": "", r"^\s+": ""}, regex=True)
    .replace(r"\n", "", regex=True)
    .dropna()
)
use_groups_cleaned

,Use Group,Uses Header,Uses (NAICS Code),R1,R2,R3,R4,R5,R6,R7,...,C3,C4,C5,C6,C7,C8,M1,M2,M3,PRC
0,X,Food Manufacturing (311),Animal food manufacturing (3111),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
1,X,Food Manufacturing (311),Sugar manufacturing (31131),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
2,X,Food Manufacturing (311),All other sugar and confectionary product manu...,–,–,–,–,–,–,–,...,–,●S P,●S P,●S P,●S P,●P,●P,●P,●P,D1
3,X,Food Manufacturing (311),Animal slaughtering and processing (3116),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
4,X,Food Manufacturing (311),Seafood product preparation and packaging (3117),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
5,X,Food Manufacturing (311),All other food manufacturing (in 311),–,–,–,–,–,–,–,...,–,●S P,●S P,●S P,●S P,●P,●P,●P,●P,D1
6,X,Beverage and Tobacco Product Manufacturing (312),Distilleries (31214),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
7,X,Beverage and Tobacco Product Manufacturing (312),All other beverage manufacturing ( in 3121 ),–,–,–,–,–,–,–,...,–,●S P,●S P,●S P,●S P,●P,●P,●P,●P,D1
8,X,Beverage and Tobacco Product Manufacturing (312),Tobacco manufacturing (3122),–,–,–,–,–,–,–,...,–,●S P,●S P,●S P,●S P,●P,●P,●P,●P,D1

In [6]:
naics_description_columns = ["Uses Header", "Uses (NAICS Code)"]
other_columns = [
    col for col in use_groups_cleaned if col not in naics_description_columns
]

use_groups_cleaned[other_columns] = use_groups_cleaned[other_columns].applymap(
    lambda x: x.replace(" ", "").strip()
)
use_groups_cleaned

C:\Users\m_carper\AppData\Local\Temp\ipykernel_18572\2938425609.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  use_groups_cleaned[other_columns] = use_groups_cleaned[other_columns].applymap(

,Use Group,Uses Header,Uses (NAICS Code),R1,R2,R3,R4,R5,R6,R7,...,C3,C4,C5,C6,C7,C8,M1,M2,M3,PRC
0,X,Food Manufacturing (311),Animal food manufacturing (3111),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
1,X,Food Manufacturing (311),Sugar manufacturing (31131),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
2,X,Food Manufacturing (311),All other sugar and confectionary product manu...,–,–,–,–,–,–,–,...,–,●SP,●SP,●SP,●SP,●P,●P,●P,●P,D1
3,X,Food Manufacturing (311),Animal slaughtering and processing (3116),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
4,X,Food Manufacturing (311),Seafood product preparation and packaging (3117),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
5,X,Food Manufacturing (311),All other food manufacturing (in 311),–,–,–,–,–,–,–,...,–,●SP,●SP,●SP,●SP,●P,●P,●P,●P,D1
6,X,Beverage and Tobacco Product Manufacturing (312),Distilleries (31214),–,–,–,–,–,–,–,...,–,–,–,–,–,–,●P,●P,●P,D1
7,X,Beverage and Tobacco Product Manufacturing (312),All other beverage manufacturing ( in 3121 ),–,–,–,–,–,–,–,...,–,●SP,●SP,●SP,●SP,●P,●P,●P,●P,D1
8,X,Beverage and Tobacco Product Manufacturing (312),Tobacco manufacturing (3122),–,–,–,–,–,–,–,...,–,●SP,●SP,●SP,●SP,●P,●P,●P,●P,D1

In [6]:
use_groups_cleaned.to_csv(OUTPUT_DIRECTORY / "use_groups_cleaned.csv", index=False)

### Full set (all UGs)

In [3]:
ug_all = pd.read_excel(RESOURCES_DIRECTORY / "Use Group Chart - Transposed All UGs.xlsx")
ug_all.head()

,Use Group,Use Header,Use Name Full,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,R1,R2,R3,...,C4,C5,C6,C7,C8,M1,M2,M3,PRC,NAICS_Type
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...","Agricultural #uses#, including greenhouses, nu...",NaN,NaN,NaN,●\nP,●\nP,●\nP,...,●\nP U,●\nP U,●\nP U,●\nP U,●\nP U,●\nP U,●\nP U,●\nP U,G,0
1,I,Open Uses,Cemeteries,Cemeteries,NaN,NaN,NaN,–\n,–\n,●\n,...,●\n,●\n,●\n,●\n,●\n,●\n,–\n,–\n,N/A\n,0
2,I,Open Uses,Golf courses,Golf courses,NaN,NaN,NaN,●\n,●\n,●\n,...,●\n,●\n,●\n,●\n,●\n,●\n,–\n,–\n,B3 and N/A\n,0
3,I,Open Uses,Outdoor racket courts,Outdoor racket courts,NaN,NaN,NaN,○,○,●\nP,...,●\nP,●\nP,●\nP,●\nP,●\nP,●\nP,–\n,–\n,G,0
4,I,Open Uses,Outdoor skating rinks,Outdoor skating rinks,NaN,NaN,NaN,○,○,●\nP,...,●\nP,●\nP,●\nP,●\n,●\n,●\n,●\n,●\n,G,0

In [4]:
ug_cleaned = (
    ug_all.replace({r"\s+$": "", r"^\s+": ""}, regex=True)
    .replace(r"\n", "", regex=True)
)

remove_columns = ["Use Name Full","PRC"]

other_columns = [
    col for col in ug_cleaned if col not in remove_columns
]

ug_cleaned = ug_cleaned[other_columns]
ug_cleaned.head()

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,R1,R2,R3,R4,...,C3,C4,C5,C6,C7,C8,M1,M2,M3,NAICS_Type
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",NaN,NaN,NaN,●P,●P,●P,●P,...,●P U,●P U,●P U,●P U,●P U,●P U,●P U,●P U,●P U,0
1,I,Open Uses,Cemeteries,NaN,NaN,NaN,–,–,●,●,...,●,●,●,●,●,●,●,–,–,0
2,I,Open Uses,Golf courses,NaN,NaN,NaN,●,●,●,●,...,●,●,●,●,●,●,●,–,–,0
3,I,Open Uses,Outdoor racket courts,NaN,NaN,NaN,○,○,●P,●P,...,●P,●P,●P,●P,●P,●P,●P,–,–,0
4,I,Open Uses,Outdoor skating rinks,NaN,NaN,NaN,○,○,●P,●P,...,●P,●P,●P,●P,●,●,●,●,●,0

In [5]:
ug_cleaned.shape

(259, 30)

## Pivot use group zoning district columns

In [6]:
id_columns = ["Use Group", "Use Header", "Use Name", "Use NAICS Code", "NAICS Notes", "NAICS to subtract", "NAICS_Type"]

use_groups_zoning_districts = ug_cleaned.melt(
    id_vars=id_columns, var_name="Zoning District", value_name="Permitted Value"
)

use_groups_zoning_districts

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,NAICS_Type,Zoning District,Permitted Value
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",NaN,NaN,NaN,0,R1,●P
1,I,Open Uses,Cemeteries,NaN,NaN,NaN,0,R1,–
2,I,Open Uses,Golf courses,NaN,NaN,NaN,0,R1,●
3,I,Open Uses,Outdoor racket courts,NaN,NaN,NaN,0,R1,○
4,I,Open Uses,Outdoor skating rinks,NaN,NaN,NaN,0,R1,○
...,...,...,...,...,...,...,...,...,...
5952,X,"Electrical Equipment, Appliance, and Component...",All other electrical equipment and component m...,in 335,"335 minus 3351, 33521, 33522",33522.0,3,M3,●P
5953,X,Transportation Equipment Manufacturing (336),Transportation equipment manufacturing (336),336,NaN,NaN,1,M3,●P
5954,X,Furniture and Related Product Manufacturing (337),Furniture and related product manufacturing (337),337,NaN,NaN,1,M3,●P
5955,X,Miscellaneous Manufacturing (339),Medical equipment and supplies manufacturing (...,3391,NaN,NaN,1,M3,●P
5956,X,Miscellaneous Manufacturing (339),Other miscellaneous manufacturing (3399),3399,NaN,NaN,1,M3,●P

In [7]:
use_groups_zoning_districts.to_csv(
    OUTPUT_DIRECTORY / "use_groups_zoning_districts_full.csv", index=False
)

## Parse use group zoning district values

In [8]:
use_groups_zoning_districts["Permitted Value"].value_counts()

Permitted Value
–                 3192
●                 1177
●P                 498
○                  381
●S     P           197
●U                 179
●P     U           133
●S                 116
●S     U            39
●S     P     U      14
♦P                  10
♦P     U            10
*                    5
♦                    3
♦S                   2
●S    U              1
Name: count, dtype: int64

In [9]:
# def parse_naics_text(naics_text: str) -> str:
#     return naics_text.split("(")[1].removesuffix(")").replace("in", "").strip()

In [10]:
PERMITTED_KEY = {
    "–": "Not permitted",
    "●": "Permitted",
    "♦": "Permitted with limitations",
    "*": "Permitted with limitations*",
    "○": "Special permit required",
    "S": "Size restriction",
    "P": "Additional conditions",
    "U": "Open use allowances",
}
PERMITTED_VALUE_COLUMNS = list(PERMITTED_KEY.values())

In [11]:
def parse_permitted_value(row: pd.Series) -> list:
    for character in PERMITTED_KEY.keys():
        if character in row["Permitted Value"]:
            row[PERMITTED_KEY[character]] = True
        else:
            row[PERMITTED_KEY[character]] = False
    return row

In [12]:
use_groups_zoning_districts = use_groups_zoning_districts.reindex(
    columns=[
        "Use Group",
        "Use Header",
        "Use Name",
        "Use NAICS Code",
        "NAICS Notes",
        "NAICS to subtract",
        "NAICS_Type",
        "Zoning District",
        "Permitted Value",
    ]
    + PERMITTED_VALUE_COLUMNS
)
use_groups_zoning_districts.head()

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,NAICS_Type,Zoning District,Permitted Value,Not permitted,Permitted,Permitted with limitations,Permitted with limitations*,Special permit required,Size restriction,Additional conditions,Open use allowances
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",NaN,NaN,NaN,0,R1,●P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I,Open Uses,Cemeteries,NaN,NaN,NaN,0,R1,–,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I,Open Uses,Golf courses,NaN,NaN,NaN,0,R1,●,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I,Open Uses,Outdoor racket courts,NaN,NaN,NaN,0,R1,○,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I,Open Uses,Outdoor skating rinks,NaN,NaN,NaN,0,R1,○,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
use_groups_zoning_districts_flags = use_groups_zoning_districts.apply(parse_permitted_value, axis=1)

use_groups_zoning_districts_flags["Use NAICS Code"] = use_groups_zoning_districts_flags["Use NAICS Code"].astype(str)
use_groups_zoning_districts_flags['Use NAICS Code'] = use_groups_zoning_districts_flags['Use NAICS Code'].str.replace(' ', '')
use_groups_zoning_districts_flags["NAICS Notes"] = use_groups_zoning_districts_flags["NAICS Notes"].astype(str)
use_groups_zoning_districts_flags["NAICS to subtract"] = use_groups_zoning_districts_flags["NAICS to subtract"].astype(str).str.split('.').str[0]

use_groups_zoning_districts_flags.head()

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,NAICS_Type,Zoning District,Permitted Value,Not permitted,Permitted,Permitted with limitations,Permitted with limitations*,Special permit required,Size restriction,Additional conditions,Open use allowances
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",nan,nan,nan,0,R1,●P,False,True,False,False,False,False,True,False
1,I,Open Uses,Cemeteries,nan,nan,nan,0,R1,–,True,False,False,False,False,False,False,False
2,I,Open Uses,Golf courses,nan,nan,nan,0,R1,●,False,True,False,False,False,False,False,False
3,I,Open Uses,Outdoor racket courts,nan,nan,nan,0,R1,○,False,False,False,False,True,False,False,False
4,I,Open Uses,Outdoor skating rinks,nan,nan,nan,0,R1,○,False,False,False,False,True,False,False,False

In [14]:
use_groups_zoning_districts_flags["Is Allowed"] = use_groups_zoning_districts_flags["Not permitted"].apply(lambda row: "No" if row else "Yes")

df_ug = use_groups_zoning_districts_flags.copy()

df_ug['Is Allowed'] = df_ug['Is Allowed'] + df_ug['Special permit required'].apply(lambda x: ', by special permit' if x else '')
df_ug['Is Allowed'] = df_ug['Is Allowed'] + df_ug['Size restriction'].apply(lambda x: ', subject to size restrictions' if x else '')
df_ug['Is Allowed'] = df_ug['Is Allowed'] + df_ug['Additional conditions'].apply(lambda x: ', subject to additional conditions' if x else '')
df_ug['Is Allowed'] = df_ug['Is Allowed'] + df_ug['Open use allowances'].apply(lambda x: ', subject to open use allowances' if x else '')
df_ug['Is Allowed'] = df_ug['Is Allowed'] + df_ug['Permitted with limitations'].apply(lambda x: ', with limited applicability' if x else '')
df_ug['Is Allowed'] = df_ug['Is Allowed'] + df_ug['Permitted with limitations*'].apply(lambda x: ', with limited applicability' if x else '')

df_ug.head()

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,NAICS_Type,Zoning District,Permitted Value,Not permitted,Permitted,Permitted with limitations,Permitted with limitations*,Special permit required,Size restriction,Additional conditions,Open use allowances,Is Allowed
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",nan,nan,nan,0,R1,●P,False,True,False,False,False,False,True,False,"Yes, subject to additional conditions"
1,I,Open Uses,Cemeteries,nan,nan,nan,0,R1,–,True,False,False,False,False,False,False,False,No
2,I,Open Uses,Golf courses,nan,nan,nan,0,R1,●,False,True,False,False,False,False,False,False,Yes
3,I,Open Uses,Outdoor racket courts,nan,nan,nan,0,R1,○,False,False,False,False,True,False,False,False,"Yes, by special permit"
4,I,Open Uses,Outdoor skating rinks,nan,nan,nan,0,R1,○,False,False,False,False,True,False,False,False,"Yes, by special permit"

In [15]:
df_ug['Is Allowed'].value_counts()

Is Allowed
No                                                                                                     3192
Yes                                                                                                    1177
Yes, subject to additional conditions                                                                   498
Yes, by special permit                                                                                  381
Yes, subject to size restrictions, subject to additional conditions                                     197
Yes, subject to open use allowances                                                                     179
Yes, subject to additional conditions, subject to open use allowances                                   133
Yes, subject to size restrictions                                                                       116
Yes, subject to size restrictions, subject to open use allowances                                        40
Yes, subject to size restrictions, subject to additional conditions, subject to open use allowances      14
Yes, subject to additional conditions, with limited applicability                                        10
Yes, subject to additional conditions, subject to open use allowances, with limited applicability        10
Yes, with limited applicability                                                                           8
Yes, subject to size restrictions, with limited applicability                                             2
Name: count, dtype: int64

In [16]:
df_ug['Use Group'].value_counts().sum()

5957

In [15]:
df_ug.to_excel(
    OUTPUT_DIRECTORY / "use_groups_zoning_districts_flags.xlsx", index=False
)

In [17]:
df_ug

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,NAICS_Type,Zoning District,Permitted Value,Not permitted,Permitted,Permitted with limitations,Permitted with limitations*,Special permit required,Size restriction,Additional conditions,Open use allowances,Is Allowed
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",nan,nan,nan,0,R1,●P,False,True,False,False,False,False,True,False,"Yes, subject to additional conditions"
1,I,Open Uses,Cemeteries,nan,nan,nan,0,R1,–,True,False,False,False,False,False,False,False,No
2,I,Open Uses,Golf courses,nan,nan,nan,0,R1,●,False,True,False,False,False,False,False,False,Yes
3,I,Open Uses,Outdoor racket courts,nan,nan,nan,0,R1,○,False,False,False,False,True,False,False,False,"Yes, by special permit"
4,I,Open Uses,Outdoor skating rinks,nan,nan,nan,0,R1,○,False,False,False,False,True,False,False,False,"Yes, by special permit"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5952,X,"Electrical Equipment, Appliance, and Component...",All other electrical equipment and component m...,in335,"335 minus 3351, 33521, 33522",33522,3,M3,●P,False,True,False,False,False,False,True,False,"Yes, subject to additional conditions"
5953,X,Transportation Equipment Manufacturing (336),Transportation equipment manufacturing (336),336,nan,nan,1,M3,●P,False,True,False,False,False,False,True,False,"Yes, subject to additional conditions"
5954,X,Furniture and Related Product Manufacturing (337),Furniture and related product manufacturing (337),337,nan,nan,1,M3,●P,False,True,False,False,False,False,True,False,"Yes, subject to additional conditions"
5955,X,Miscellaneous Manufacturing (339),Medical equipment and supplies manufacturing (...,3391,nan,nan,1,M3,●P,False,True,False,False,False,False,True,False,"Yes, subject to additional conditions"
5956,X,Miscellaneous Manufacturing (339),Other miscellaneous manufacturing (3399),3399,nan,nan,1,M3,●P,False,True,False,False,False,False,True,False,"Yes, subject to additional conditions"

## Add ZR Links
For additional conditions, size limitations, etc.

In [18]:
residential_dist_reg_links = {'UGI - gen': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-111',
                            'UGI - addl cond': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-112',
                            'UGI - special perm': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-113',
                            'UGI - addl park': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-114',
                            'UGII - gen': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-121',
                            'UGII - addl cond': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-122',
                            'UGIII - gen': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-131',
                            'UGIII - size': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-132',
                            'UGIII - addl cond': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-133',
                            'UGIII - special perm': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-134',
                            'UGIII - addl park': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-135',
                            'UGIV - gen': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-141',
                            'UGIV - size': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-142',
                            'UGIV - addl cond': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-143',
                            'UGIV - special perm': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-144',
                            'UGV - ALL': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-15',
                            'UGVII - ALL': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-17',
                            'UGVIII - ALL': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-18',
                            'Adult Establishments': 'https://zr.planning.nyc.gov/article-ii/chapter-2#22-01'}

In [19]:
commercial_dist_reg_links = {'UGI - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-111',
                            'UGI - size': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-112',
                            'UGI - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-113',
                            'UGI - open use': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-114',
                            'UGI - special perm': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-115',
                            'UGI - addl park': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-116',
                            'UGII - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-121',
                            'UGII - limited appl': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-122',
                            'UGII - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-123',
                            'UGIII - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-131',
                            'UGIII - size': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-132',
                            'UGIII - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-133',
                            'UGIII - special perm': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-134',
                            'UGIII - addl park': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-135',
                            'UGIV - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-141',
                            'UGIV - size': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-142',
                            'UGIV - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-143',
                            'UGIV - open use': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-144',
                            'UGIV - special perm': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-145',
                            'UGV - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-151',
                            'UGV - limited appl': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-152',
                            'UGV - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-153',
                            'UGV - open use': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-154',
                            'UGV - special perm': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-155',
                            'UGV - addl park': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-156',
                            'UGVI - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-161',
                            'UGVI - size': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-162',
                            'UGVI - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-163',
                            'UGVI - open use': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-164',
                            'UGVI - special perm': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-165',
                            'UGVI - addl park': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-166',
                            'UGVII - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-171',
                            'UGVII - limited appl': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-172',
                            'UGVII - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-173',
                            'UGVIII - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-181',
                            'UGVIII - size': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-182',
                            'UGVIII - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-183',
                            'UGVIII - open use': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-184',
                            'UGVIII - special perm': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-185',
                            'UGVIII - addl park': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-186',
                            'UGIX - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-191',
                            'UGIX - limited appl': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-192',
                            'UGIX - size': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-193',
                            'UGIX - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-194',
                            'UGIX - open use': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-195',
                            'UGIX - special perm': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-196',
                            'UGIX - addl park': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-197',
                            'UGX - gen': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-201',
                            'UGX - size': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-202',
                            'UGX - addl cond': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-203',
                            'UGX - addl park': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-204',
                            'Adult Establishments': 'https://zr.planning.nyc.gov/article-iii/chapter-2#32-01'}

In [20]:
manufacturing_dist_reg_links = {'UGI - gen': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-111',
                            'UGI - addl cond': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-112',
                            'UGI - open use': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-113',
                            'UGI - special perm': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-114',
                            'UGI - addl park': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-115',
                            'UGII - ALL': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-12',
                            'UGIII - gen': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-131',
                            'UGIII - addl cond': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-132',
                            'UGIII - special perm': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-133',
                            'UGIII - addl park': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-134',
                            'UGIV - gen': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-141',
                            'UGIV - size': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-142',
                            'UGIV - addl cond': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-143',
                            'UGIV - open use': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-144',
                            'UGIV - special perm': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-145',
                            'UGV - gen': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-151',
                            'UGV - addl cond': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-152',
                            'UGV - open use': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-153',
                            'UGV - addl park': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-154',
                            'UGVI - gen': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-161',
                            'UGVI - size': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-162',
                            'UGVI - addl cond': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-163',
                            'UGVI - open use': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-164',
                            'UGVI - addl park': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-165',
                            'UGVII - ALL': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-17',
                            'UGVIII - gen': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-181',
                            'UGVIII - size': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-182',
                            'UGVIII - addl cond': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-183',
                            'UGVIII - open use': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-184',
                            'UGVIII - special perm': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-185',
                            'UGVIII - addl park': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-186',
                            'UGIX - gen': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-191',
                            'UGIX - limited appl': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-192',
                            'UGIX - addl cond': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-193',
                            'UGIX - open use': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-194',
                            'UGX - gen': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-201',
                            'UGX - addl cond': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-202',
                            'Adult Establishments': 'https://zr.planning.nyc.gov/article-iv/chapter-2#42-01'}

In [21]:
df_ug['Limitations'], df_ug['Special Permit'], df_ug['Size Restrictions'], df_ug['Additional Conditions'], df_ug['Open Use Allowances'] = '','','','',''

In [22]:
import time

start_time = time.time()
ug_dist_link_test_df = df_ug.copy()
# ug_dist_link_test_df = df_ug_naicsTEST_.copy()

numerals = r'\b[IVX]+\b'

for index, row in ug_dist_link_test_df.iterrows():

    if row['Zoning District'][:1]=='R':
        if row['Permitted with limitations']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Limitations'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - limited appl"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Limitations'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Permitted with limitations*']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Limitations'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - limited appl"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Limitations'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Special permit required']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Special Permit'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - special perm"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Special Permit'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Size restriction']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Size Restrictions'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - size"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Size Restrictions'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Additional conditions']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Additional Conditions'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - addl cond"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Additional Conditions'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Open use allowances']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Open Use Allowances'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - open use"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Open Use Allowances'] = residential_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
            
    elif row['Zoning District'][:1]=='C':
        if row['Permitted with limitations']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Limitations'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - limited appl"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Limitations'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Permitted with limitations*']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Limitations'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - limited appl"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Limitations'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Special permit required']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Special Permit'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - special perm"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Special Permit'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Size restriction']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Size Restrictions'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - size"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Size Restrictions'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Additional conditions']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Additional Conditions'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - addl cond"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Additional Conditions'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Open use allowances']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Open Use Allowances'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - open use"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Open Use Allowances'] = commercial_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
            
    elif row['Zoning District'][:1]=='M':
        if row['Permitted with limitations']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Limitations'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - limited appl"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Limitations'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Permitted with limitations*']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Limitations'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - limited appl"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Limitations'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Special permit required']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Special Permit'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - special perm"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Special Permit'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Size restriction']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Size Restrictions'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - size"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Size Restrictions'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Additional conditions']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Additional Conditions'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - addl cond"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Additional Conditions'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
        if row['Open use allowances']==True:
            try:
                ug_dist_link_test_df.loc[index, 'Open Use Allowances'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - open use"]
            except KeyError:
                ug_dist_link_test_df.loc[index, 'Open Use Allowances'] = manufacturing_dist_reg_links[f"UG{re.findall(numerals, row['Use Group'])[0]} - ALL"]
            
end_time = time.time()
execution_time = end_time - start_time

print(f"Execution time: {execution_time:.6f} seconds")

Execution time: 0.818413 seconds

In [23]:
ug_dist_link_test_df.head()

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,NAICS_Type,Zoning District,Permitted Value,Not permitted,...,Special permit required,Size restriction,Additional conditions,Open use allowances,Is Allowed,Limitations,Special Permit,Size Restrictions,Additional Conditions,Open Use Allowances
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",nan,nan,nan,0,R1,●P,False,...,False,False,True,False,"Yes, subject to additional conditions",,,,https://zr.planning.nyc.gov/article-ii/chapter...,
1,I,Open Uses,Cemeteries,nan,nan,nan,0,R1,–,True,...,False,False,False,False,No,,,,,
2,I,Open Uses,Golf courses,nan,nan,nan,0,R1,●,False,...,False,False,False,False,Yes,,,,,
3,I,Open Uses,Outdoor racket courts,nan,nan,nan,0,R1,○,False,...,True,False,False,False,"Yes, by special permit",,https://zr.planning.nyc.gov/article-ii/chapter...,,,
4,I,Open Uses,Outdoor skating rinks,nan,nan,nan,0,R1,○,False,...,True,False,False,False,"Yes, by special permit",,https://zr.planning.nyc.gov/article-ii/chapter...,,,

In [24]:
# Use Excel formula to format strings as hyperlinks
ug_table_output = ug_dist_link_test_df.copy()

ug_table_output['Limitations'] = ug_table_output['Limitations'].apply(lambda x: f'=HYPERLINK("{x}", "{x}")' if x else '')
ug_table_output['Special Permit'] = ug_table_output['Special Permit'].apply(lambda x: f'=HYPERLINK("{x}", "{x}")' if x else '')
ug_table_output['Size Restrictions'] = ug_table_output['Size Restrictions'].apply(lambda x: f'=HYPERLINK("{x}", "{x}")' if x else '')
ug_table_output['Additional Conditions'] = ug_table_output['Additional Conditions'].apply(lambda x: f'=HYPERLINK("{x}", "{x}")' if x else '')
ug_table_output['Open Use Allowances'] = ug_table_output['Open Use Allowances'].apply(lambda x: f'=HYPERLINK("{x}", "{x}")' if x else '')
ug_table_output.head(1)

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,NAICS_Type,Zoning District,Permitted Value,Not permitted,...,Special permit required,Size restriction,Additional conditions,Open use allowances,Is Allowed,Limitations,Special Permit,Size Restrictions,Additional Conditions,Open Use Allowances
0,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",nan,nan,nan,0,R1,●P,False,...,False,False,True,False,"Yes, subject to additional conditions",,,,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...",

In [25]:
# Add for ZR Link text - add link name with specific article/section
ug_table_output['Use Name'] = ug_table_output['Use Name'].apply(lambda x: f'=HYPERLINK("https://zoningresolution.planning.nyc.gov/article-i/chapter-2#12-10", "{x}")' if (x.find("#")!=-1) else x)
ug_table_output.head()

,Use Group,Use Header,Use Name,Use NAICS Code,NAICS Notes,NAICS to subtract,NAICS_Type,Zoning District,Permitted Value,Not permitted,...,Special permit required,Size restriction,Additional conditions,Open use allowances,Is Allowed,Limitations,Special Permit,Size Restrictions,Additional Conditions,Open Use Allowances
0,I,Agriculture,"=HYPERLINK(""https://zoningresolution.planning....",nan,nan,nan,0,R1,●P,False,...,False,False,True,False,"Yes, subject to additional conditions",,,,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...",
1,I,Open Uses,Cemeteries,nan,nan,nan,0,R1,–,True,...,False,False,False,False,No,,,,,
2,I,Open Uses,Golf courses,nan,nan,nan,0,R1,●,False,...,False,False,False,False,Yes,,,,,
3,I,Open Uses,Outdoor racket courts,nan,nan,nan,0,R1,○,False,...,True,False,False,False,"Yes, by special permit",,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...",,,
4,I,Open Uses,Outdoor skating rinks,nan,nan,nan,0,R1,○,False,...,True,False,False,False,"Yes, by special permit",,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...",,,

### Output pre-NAICS join table

In [29]:
ug_table_final = ug_table_output[['Use Group','Use Header','Use Name','Zoning District','Is Allowed','Limitations',
                                  'Special Permit','Size Restrictions','Additional Conditions','Open Use Allowances']]
ug_table_final.head()

,Use Group,Use Header,Use Name,Zoning District,Is Allowed,Limitations,Special Permit,Size Restrictions,Additional Conditions,Open Use Allowances
0,I,Agriculture,"=HYPERLINK(""https://zoningresolution.planning....",R1,"Yes, subject to additional conditions",,,,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...",
1,I,Open Uses,Cemeteries,R1,No,,,,,
2,I,Open Uses,Golf courses,R1,Yes,,,,,
3,I,Open Uses,Outdoor racket courts,R1,"Yes, by special permit",,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...",,,
4,I,Open Uses,Outdoor skating rinks,R1,"Yes, by special permit",,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...",,,

In [30]:
ug_table_final.to_excel(
    OUTPUT_DIRECTORY / "usegroups_by_zoningdist_with_ZR_links.xlsx", index=False
)

## Join NAICS Codes from 6-Digit Index File

In [26]:
naics_6digit = pd.read_excel(RESOURCES_DIRECTORY / "2022_NAICS_Index_File.xlsx")
naics_6digit['NAICS22']=naics_6digit['NAICS22'].astype(str)
naics_6digit.head()

  NAICS22                             INDEX ITEM DESCRIPTION
0  111110         Soybean farming, field and seed production
1  111120          Canola farming, field and seed production
2  111120        Flaxseed farming, field and seed production
3  111120    Mustard seed farming, field and seed production
4  111120  Oilseed farming (except soybean), field and se...

In [27]:
naics_6digit['NAICS22_3dig'] = naics_6digit['NAICS22'].str[:3]
naics_6digit['NAICS22_4dig'] = naics_6digit['NAICS22'].str[:4]
naics_6digit['NAICS22_5dig'] = naics_6digit['NAICS22'].str[:5]
naics_6digit['NAICS22_6dig'] = naics_6digit['NAICS22'].str[:6]

naics_6digit.head()

,NAICS22,INDEX ITEM DESCRIPTION,NAICS22_3dig,NAICS22_4dig,NAICS22_5dig,NAICS22_6dig
0,111110,"Soybean farming, field and seed production",111,1111,11111,111110
1,111120,"Canola farming, field and seed production",111,1111,11112,111120
2,111120,"Flaxseed farming, field and seed production",111,1111,11112,111120
3,111120,"Mustard seed farming, field and seed production",111,1111,11112,111120
4,111120,"Oilseed farming (except soybean), field and se...",111,1111,11112,111120

In [28]:
df_ug_naics_single = ug_table_output[ug_table_output['NAICS_Type']==1]
df_ug_naics_list = ug_table_output[ug_table_output['NAICS_Type']==2]
df_ug_naics_within = ug_table_output[ug_table_output['NAICS_Type']==3]
df_ug_allother = ug_table_output[ug_table_output['NAICS_Type']==0]

df_ug_naics3 = df_ug_naics_single[df_ug_naics_single['Use NAICS Code'].str.len()==3]
df_ug_naics4 = df_ug_naics_single[df_ug_naics_single['Use NAICS Code'].str.len()==4]
df_ug_naics5 = df_ug_naics_single[df_ug_naics_single['Use NAICS Code'].str.len()==5]
df_ug_naics6 = df_ug_naics_single[df_ug_naics_single['Use NAICS Code'].str.len()==6]

df_ug_naics3_list = df_ug_naics_list[df_ug_naics_list['NAICS Notes'].str.len()==3]
df_ug_naics4_list = df_ug_naics_list[df_ug_naics_list['NAICS Notes'].str.len()==4]
df_ug_naics5_list = df_ug_naics_list[df_ug_naics_list['NAICS Notes'].str.len()==5]
df_ug_naics6_list = df_ug_naics_list[df_ug_naics_list['NAICS Notes'].str.len()==6]

df_ug_naics_within["Use NAICS Code"] = df_ug_naics_within["Use NAICS Code"].astype(str).str.split('in').str[1]
df_ug_naics3_within = df_ug_naics_within[df_ug_naics_within['Use NAICS Code'].str.len()==3]
df_ug_naics4_within = df_ug_naics_within[df_ug_naics_within['Use NAICS Code'].str.len()==4]
df_ug_naics5_within = df_ug_naics_within[df_ug_naics_within['Use NAICS Code'].str.len()==5]
df_ug_naics6_within = df_ug_naics_within[df_ug_naics_within['Use NAICS Code'].str.len()==6]

df_ug_naics3.shape,df_ug_naics4.shape,df_ug_naics5.shape,df_ug_naics6.shape,df_ug_naics3_list.shape,df_ug_naics4_list.shape,df_ug_naics5_list.shape,df_ug_naics6_list.shape,df_ug_naics3_within.shape,df_ug_naics4_within.shape,df_ug_naics5_within.shape,df_ug_naics6_within.shape

C:\Users\m_carper\AppData\Local\Temp\ipykernel_13192\4293716039.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ug_naics_within["Use NAICS Code"] = df_ug_naics_within["Use NAICS Code"].astype(str).str.split('in').str[1]

((184, 23),
 (1219, 23),
 (276, 23),
 (138, 23),
 (0, 23),
 (391, 23),
 (0, 23),
 (0, 23),
 (322, 23),
 (322, 23),
 (0, 23),
 (0, 23))

In [29]:
df_ug_naics3_joined = pd.merge(df_ug_naics3, naics_6digit, left_on='Use NAICS Code', right_on='NAICS22_3dig', how='inner')
df_ug_naics4_joined = pd.merge(df_ug_naics4, naics_6digit, left_on='Use NAICS Code', right_on='NAICS22_4dig', how='inner')
df_ug_naics5_joined = pd.merge(df_ug_naics5, naics_6digit, left_on='Use NAICS Code', right_on='NAICS22_5dig', how='inner')
df_ug_naics6_joined = pd.merge(df_ug_naics6, naics_6digit, left_on='Use NAICS Code', right_on='NAICS22_6dig', how='inner')

df_ug_naics3_list_joined = pd.merge(df_ug_naics3_list, naics_6digit, left_on='NAICS Notes', right_on='NAICS22_3dig', how='inner')
df_ug_naics4_list_joined = pd.merge(df_ug_naics4_list, naics_6digit, left_on='NAICS Notes', right_on='NAICS22_4dig', how='inner')
df_ug_naics5_list_joined = pd.merge(df_ug_naics5_list, naics_6digit, left_on='NAICS Notes', right_on='NAICS22_5dig', how='inner')
df_ug_naics6_list_joined = pd.merge(df_ug_naics6_list, naics_6digit, left_on='NAICS Notes', right_on='NAICS22_6dig', how='inner')

df_ug_naics3_within_joined = pd.merge(df_ug_naics3_within, naics_6digit, left_on='Use NAICS Code', right_on='NAICS22_3dig', how='inner')
df_ug_naics4_within_joined = pd.merge(df_ug_naics4_within, naics_6digit, left_on='Use NAICS Code', right_on='NAICS22_4dig', how='inner')
df_ug_naics5_within_joined = pd.merge(df_ug_naics5_within, naics_6digit, left_on='Use NAICS Code', right_on='NAICS22_5dig', how='inner')
df_ug_naics6_within_joined = pd.merge(df_ug_naics6_within, naics_6digit, left_on='Use NAICS Code', right_on='NAICS22_6dig', how='inner')

df_ug_naics3_within_joined_ = df_ug_naics3_within_joined[(df_ug_naics3_within_joined['NAICS22_3dig']!=df_ug_naics3_within_joined['NAICS to subtract'])&(df_ug_naics3_within_joined['NAICS22_4dig']!=df_ug_naics3_within_joined['NAICS to subtract'])&(df_ug_naics3_within_joined['NAICS22_5dig']!=df_ug_naics3_within_joined['NAICS to subtract'])&(df_ug_naics3_within_joined['NAICS22_6dig']!=df_ug_naics3_within_joined['NAICS to subtract'])]
df_ug_naics4_within_joined_ = df_ug_naics4_within_joined[(df_ug_naics4_within_joined['NAICS22_3dig']!=df_ug_naics4_within_joined['NAICS to subtract'])&(df_ug_naics4_within_joined['NAICS22_4dig']!=df_ug_naics4_within_joined['NAICS to subtract'])&(df_ug_naics4_within_joined['NAICS22_5dig']!=df_ug_naics4_within_joined['NAICS to subtract'])&(df_ug_naics4_within_joined['NAICS22_6dig']!=df_ug_naics4_within_joined['NAICS to subtract'])]
df_ug_naics5_within_joined_ = df_ug_naics5_within_joined[(df_ug_naics5_within_joined['NAICS22_3dig']!=df_ug_naics5_within_joined['NAICS to subtract'])&(df_ug_naics5_within_joined['NAICS22_4dig']!=df_ug_naics5_within_joined['NAICS to subtract'])&(df_ug_naics5_within_joined['NAICS22_5dig']!=df_ug_naics5_within_joined['NAICS to subtract'])&(df_ug_naics5_within_joined['NAICS22_6dig']!=df_ug_naics5_within_joined['NAICS to subtract'])]
df_ug_naics6_within_joined_ = df_ug_naics6_within_joined[(df_ug_naics6_within_joined['NAICS22_3dig']!=df_ug_naics6_within_joined['NAICS to subtract'])&(df_ug_naics6_within_joined['NAICS22_4dig']!=df_ug_naics6_within_joined['NAICS to subtract'])&(df_ug_naics6_within_joined['NAICS22_5dig']!=df_ug_naics6_within_joined['NAICS to subtract'])&(df_ug_naics6_within_joined['NAICS22_6dig']!=df_ug_naics6_within_joined['NAICS to subtract'])]

df_ug_naics3_joined.shape,df_ug_naics4_joined.shape,df_ug_naics5_joined.shape,df_ug_naics6_joined.shape,df_ug_naics3_list_joined.shape,df_ug_naics4_list_joined.shape,df_ug_naics5_list_joined.shape,df_ug_naics6_list_joined.shape,df_ug_naics3_within_joined.shape,df_ug_naics4_within_joined.shape,df_ug_naics5_within_joined.shape,df_ug_naics6_within_joined.shape

((75693, 29),
 (73370, 29),
 (8004, 29),
 (2323, 29),
 (0, 29),
 (16238, 29),
 (0, 29),
 (0, 29),
 (228919, 29),
 (27048, 29),
 (0, 29),
 (0, 29))

In [30]:
df_ug_naics = pd.concat([df_ug_naics3_joined,df_ug_naics4_joined,df_ug_naics5_joined,df_ug_naics6_joined,
                        df_ug_naics3_list_joined,df_ug_naics4_list_joined,df_ug_naics5_list_joined,df_ug_naics6_list_joined,
            df_ug_naics3_within_joined_,df_ug_naics4_within_joined_,df_ug_naics5_within_joined_,df_ug_naics6_within_joined_])
df_ug_naics_ = pd.concat([df_ug_naics,df_ug_allother])
df_ug_naics.shape, df_ug_naics_.shape

((393369, 29), (396474, 29))

## Output Final Table

In [31]:
ug_table_final = df_ug_naics_[['Use Group','Use Header','Use Name','NAICS22','INDEX ITEM DESCRIPTION',
                            'Zoning District','Is Allowed','Limitations','Special Permit','Size Restrictions',
                            'Additional Conditions','Open Use Allowances']]
ug_table_final.rename(columns={'NAICS22':'NAICS Code (6-Digit)','INDEX ITEM DESCRIPTION':'NAICS Index Name'},inplace=True)
ug_table_final.head()

C:\Users\m_carper\AppData\Local\Temp\ipykernel_38788\543162349.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ug_table_final.rename(columns={'NAICS22':'NAICS Code (6-Digit)','INDEX ITEM DESCRIPTION':'NAICS Index Name'},inplace=True)

,Use Group,Use Header,Use Name,NAICS Code (6-Digit),NAICS Index Name,Zoning District,Is Allowed,Limitations,Special Permit,Size Restrictions,Additional Conditions,Open Use Allowances
0,X,Textile & Textile Product Mills (313 - 314),Textile mills (313),313110,Acetate spun yarns made from purchased fiber,R1,No,,,,,
1,X,Textile & Textile Product Mills (313 - 314),Textile mills (313),313110,"Acrylic and modacrylic filament yarn throwing,...",R1,No,,,,,
2,X,Textile & Textile Product Mills (313 - 314),Textile mills (313),313110,Acrylic spun yarns made from purchased fiber,R1,No,,,,,
3,X,Textile & Textile Product Mills (313 - 314),Textile mills (313),313110,Animal fiber yarn twisting or winding of purch...,R1,No,,,,,
4,X,Textile & Textile Product Mills (313 - 314),Textile mills (313),313110,"Bags, hemp, made from purchased fiber",R1,No,,,,,

In [32]:
ug_table_final = ug_table_final.sort_values(by=['Zoning District','Use Group','Use Header','Use Name'])
ug_table_final.head()

,Use Group,Use Header,Use Name,NAICS Code (6-Digit),NAICS Index Name,Zoning District,Is Allowed,Limitations,Special Permit,Size Restrictions,Additional Conditions,Open Use Allowances
3108,I,Agriculture,"Agricultural #uses#, including greenhouses, nu...",NaN,NaN,C1,"Yes, subject to size restrictions, subject to ...",,,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...","=HYPERLINK(""https://zr.planning.nyc.gov/articl...","=HYPERLINK(""https://zr.planning.nyc.gov/articl..."
3113,I,Open Uses,#Public parks# or playgrounds or private parks,NaN,NaN,C1,Yes,,,,,
3109,I,Open Uses,Cemeteries,NaN,NaN,C1,Yes,,,,,
3110,I,Open Uses,Golf courses,NaN,NaN,C1,Yes,,,,,
3111,I,Open Uses,Outdoor racket courts,NaN,NaN,C1,"Yes, subject to additional conditions",,,,"=HYPERLINK(""https://zr.planning.nyc.gov/articl...",

In [33]:
ug_table_final.shape

(396474, 12)

In [34]:
ug_table_final.to_excel(
    OUTPUT_DIRECTORY / "usegroups_by_zoningdist_with_ZR_links_NAICS_JOIN_3.xlsx", index=False
)